/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2024-12-30 14:21:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.Map;

public final class updateAccountDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    Map<String, String> userDetails = (Map<String, String>) request.getAttribute("userDetails");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Contul meu</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/ddeStore/css/user.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("    	.container {\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            margin: 50px auto;\r\n");
      out.write("        }\r\n");
      out.write("		.list-group-item:hover {\r\n");
      out.write("		    background-color: #495057; \r\n");
      out.write("		    color: #f8f9fa;\r\n");
      out.write("		}\r\n");
      out.write("		.btn-warning:hover {\r\n");
      out.write("		    background-color: #e0a800;\r\n");
      out.write("		}\r\n");
      out.write("		.btn-danger:hover {\r\n");
      out.write("		    background-color: #bd2130;\r\n");
      out.write("		}\r\n");
      out.write("		.border-top-white {\r\n");
      out.write("		    border-top: 1px solid white !important;\r\n");
      out.write("		    border-bottom: 0; \r\n");
      out.write("		    border-right: 0;\r\n");
      out.write("		    border-left: 0;\r\n");
      out.write("		    padding: 15px;\r\n");
      out.write("		}\r\n");
      out.write("		.border-bottom-white {\r\n");
      out.write("		    border-bottom: 1px solid white ; \r\n");
      out.write("		    border-right: 0;\r\n");
      out.write("		    border-left: 0;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.notification {\r\n");
      out.write("		    position: fixed;\r\n");
      out.write("		    bottom: 20px;\r\n");
      out.write("		    right: 20px;\r\n");
      out.write("		    background-color: #28a745; /* Verde */\r\n");
      out.write("		    color: white;\r\n");
      out.write("		    padding: 15px 20px;\r\n");
      out.write("		    border-radius: 5px;\r\n");
      out.write("		    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("		    font-size: 14px;\r\n");
      out.write("		    z-index: 1000;\r\n");
      out.write("		    display: none; /* Ascuns implicit */\r\n");
      out.write("		    animation: fadeIn 0.5s, fadeOut 0.5s 2.5s;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		/* AnimaÈii pentru popup */\r\n");
      out.write("		@keyframes fadeIn {\r\n");
      out.write("		    from {\r\n");
      out.write("		        opacity: 0;\r\n");
      out.write("		        transform: translateY(10px);\r\n");
      out.write("		    }\r\n");
      out.write("		    to {\r\n");
      out.write("		        opacity: 1;\r\n");
      out.write("		        transform: translateY(0);\r\n");
      out.write("		    }\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		@keyframes fadeOut {\r\n");
      out.write("		    from {\r\n");
      out.write("		        opacity: 1;\r\n");
      out.write("		        transform: translateY(0);\r\n");
      out.write("		    }\r\n");
      out.write("		    to {\r\n");
      out.write("		        opacity: 0;\r\n");
      out.write("		        transform: translateY(10px);\r\n");
      out.write("		    }\r\n");
      out.write("		}\r\n");
      out.write("				\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- Main Container -->\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("	    <div class=\"row\">\r\n");
      out.write("	        <!-- Sidebar -->\r\n");
      out.write("	        <div class=\"col-md-2 bg-dark text-light p-3\" style=\"height: 100vh;\">\r\n");
      out.write("	        	<div class=\"container-fluid\">\r\n");
      out.write("		            <a class=\"navbar-brand\" href=\"/ddeStore/ProductFilterServlet\">\r\n");
      out.write("		                <img src=\"/ddeStore/assets/logo2.jpg\" alt=\"Logo\" style=\"width: 150px; heigh:auto; margin-bottom:25px;\">\r\n");
      out.write("		            </a>\r\n");
      out.write("		        </div>\r\n");
      out.write("	            \r\n");
      out.write("	            <ul class=\"list-group bg-dark\">\r\n");
      out.write("	            	\r\n");
      out.write("	                <li class=\"list-group-item bg-dark text-light border-top-white\">\r\n");
      out.write("	                    <a href=\"/ddeStore/CartServlet\" class=\"text-decoration-none text-light\">Cos de cumparaturi</a>\r\n");
      out.write("	                </li>\r\n");
      out.write("	                <li class=\"list-group-item bg-dark text-light border-top-white\">\r\n");
      out.write("	                    <a href=\"/ddeStore/FavoritesServlet\" class=\"text-decoration-none text-light\">Lista favorite</a>\r\n");
      out.write("	                </li>\r\n");
      out.write("	                <li class=\"list-group-item bg-dark text-light border-top-white\">\r\n");
      out.write("	                    <a href=\"/ddeStore/AccountDetailsServlet\" class=\"text-decoration-none text-light\">Detalii cont</a>\r\n");
      out.write("	                </li>\r\n");
      out.write("	                <li class=\"list-group-item bg-dark text-light border-top-white border-bottom-white\">\r\n");
      out.write("	                    <a href=\"/ddeStore/OrderHistoryServlet\" class=\"text-decoration-none text-light\">Istoric comenzi</a>\r\n");
      out.write("	                </li>\r\n");
      out.write("	            </ul>\r\n");
      out.write("	            <div class=\" text-center\" style=\"margin-top: 320px;\">\r\n");
      out.write("	                <a href=\"/ddeStore/ProductFilterServlet\" class=\"btn btn-warning w-100\">Inapoi la produse</a>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\" text-center\" style=\"margin-top: 10px;\">\r\n");
      out.write("	                <a href=\"/ddeStore/logout\" class=\"btn btn-danger w-100\">Logout</a>\r\n");
      out.write("	            </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	\r\n");
      out.write("	        <!-- Main Content -->\r\n");
      out.write("	        <div class=\"col-md-9 d-flex justify-content-center align-items-center\">\r\n");
      out.write("	            <div class=\"container mt-5\">\r\n");
      out.write("			    <h2 class=\"mb-4\">Editeaza Detaliile Contului</h2>\r\n");
      out.write("			    <form action=\"/ddeStore/AccountDetailsServlet\" method=\"post\">\r\n");
      out.write("			        <!-- Nume Èi Prenume -->\r\n");
      out.write("			        <div class=\"row mb-3\">\r\n");
      out.write("			            <div class=\"col-md-6\">\r\n");
      out.write("			                <label for=\"nume\" class=\"form-label\">Nume</label>\r\n");
      out.write("			                <input type=\"text\" class=\"form-control\" id=\"nume\" name=\"nume\" value=\"");
      out.print( userDetails.get("Nume") );
      out.write("\" required>\r\n");
      out.write("			            </div>\r\n");
      out.write("			            <div class=\"col-md-6\">\r\n");
      out.write("			                <label for=\"prenume\" class=\"form-label\">Prenume</label>\r\n");
      out.write("			                <input type=\"text\" class=\"form-control\" id=\"prenume\" name=\"prenume\" value=\"");
      out.print( userDetails.get("Prenume") );
      out.write("\" required>\r\n");
      out.write("			            </div>\r\n");
      out.write("			        </div>\r\n");
      out.write("			        \r\n");
      out.write("			        <!-- Email -->\r\n");
      out.write("			        <div class=\"row mb-3\">\r\n");
      out.write("			            <div class=\"col-md-12\">\r\n");
      out.write("			                <label for=\"email\" class=\"form-label\">Email</label>\r\n");
      out.write("			                <input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" value=\"");
      out.print( userDetails.get("Email") );
      out.write("\" required>\r\n");
      out.write("			            </div>\r\n");
      out.write("			        </div>\r\n");
      out.write("			        \r\n");
      out.write("			        <!-- Parola veche Èi telefon -->\r\n");
      out.write("			        <div class=\"row mb-3\">\r\n");
      out.write("			            <div class=\"col-md-6\">\r\n");
      out.write("			                <label for=\"parolaVeche\" class=\"form-label\">Parola Veche</label>\r\n");
      out.write("			                <input type=\"password\" class=\"form-control\" id=\"parolaVeche\" name=\"parolaVeche\" value=\"");
      out.print( userDetails.get("Parola") );
      out.write("\" readonly>\r\n");
      out.write("			            </div>\r\n");
      out.write("			            <div class=\"col-md-6\">\r\n");
      out.write("			                <label for=\"telefon\" class=\"form-label\">Telefon</label>\r\n");
      out.write("			                <input type=\"text\" class=\"form-control\" id=\"telefon\" name=\"telefon\" value=\"");
      out.print( userDetails.get("Telefon") );
      out.write("\" required>\r\n");
      out.write("			            </div>\r\n");
      out.write("			        </div>\r\n");
      out.write("			        <!-- parola noua -->\r\n");
      out.write("			        <div class=\"row mb-3\">\r\n");
      out.write("			            <div class=\"col-md-12\">\r\n");
      out.write("			                <label for=\"parolaNoua\" class=\"form-label\">Parola Noua</label>\r\n");
      out.write("			                <input type=\"password\" class=\"form-control\" id=\"parolaNoua\" name=\"parolaNoua\" placeholder=\"Introduceti parola noua (doar daca doriti sa o schimbati)\">\r\n");
      out.write("			            </div>\r\n");
      out.write("			        </div>\r\n");
      out.write("			        \r\n");
      out.write("			        <!-- OraÈ Èi JudeÈ -->\r\n");
      out.write("			        <div class=\"row mb-3\">\r\n");
      out.write("			            <div class=\"col-md-6\">\r\n");
      out.write("			                <label for=\"oras\" class=\"form-label\">Oras</label>\r\n");
      out.write("			                <input type=\"text\" class=\"form-control\" id=\"oras\" name=\"oras\" value=\"");
      out.print( userDetails.get("Oras") );
      out.write("\" required>\r\n");
      out.write("			            </div>\r\n");
      out.write("			            <div class=\"col-md-6\">\r\n");
      out.write("			                <label for=\"judet\" class=\"form-label\">Judet</label>\r\n");
      out.write("			                <input type=\"text\" class=\"form-control\" id=\"judet\" name=\"judet\" value=\"");
      out.print( userDetails.get("Judet") );
      out.write("\" required>\r\n");
      out.write("			            </div>\r\n");
      out.write("			        </div>\r\n");
      out.write("			        \r\n");
      out.write("			        <!-- Strada Èi NumÄr -->\r\n");
      out.write("			        <div class=\"row mb-3\">\r\n");
      out.write("			            <div class=\"col-md-6\">\r\n");
      out.write("			                <label for=\"strada\" class=\"form-label\">Strada</label>\r\n");
      out.write("			                <input type=\"text\" class=\"form-control\" id=\"strada\" name=\"strada\" value=\"");
      out.print( userDetails.get("Strada") );
      out.write("\" required>\r\n");
      out.write("			            </div>\r\n");
      out.write("			            <div class=\"col-md-6\">\r\n");
      out.write("			                <label for=\"numar\" class=\"form-label\">Numar</label>\r\n");
      out.write("			                <input type=\"text\" class=\"form-control\" id=\"numar\" name=\"numar\" value=\"");
      out.print( userDetails.get("Numar") );
      out.write("\" required>\r\n");
      out.write("			            </div>\r\n");
      out.write("			        </div>\r\n");
      out.write("			        \r\n");
      out.write("			        <!-- Submit Button -->\r\n");
      out.write("			        <div class=\"row\">\r\n");
      out.write("			            <div class=\"col-md-12 text-center\">\r\n");
      out.write("			                <button type=\"submit\" class=\"btn btn-success w-100\">Salveaza</button>\r\n");
      out.write("			            </div>\r\n");
      out.write("			        </div>\r\n");
      out.write("			    </form>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	        </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"notification\" id=\"successNotification\">\r\n");
      out.write("	    Modificarile au fost salvate cu succes!\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("	    document.querySelector(\"form\").addEventListener(\"submit\", function (event) {\r\n");
      out.write("	        event.preventDefault(); // Previne submit-ul implicit al formularului\r\n");
      out.write("	\r\n");
      out.write("	        // AfiÈeazÄ notificarea\r\n");
      out.write("	        const notification = document.getElementById(\"successNotification\");\r\n");
      out.write("	        notification.style.display = \"block\";\r\n");
      out.write("	\r\n");
      out.write("	        // DupÄ 3 secunde, ascunde notificarea Èi redirecÈioneazÄ\r\n");
      out.write("	        setTimeout(() => {\r\n");
      out.write("	            notification.style.display = \"none\";\r\n");
      out.write("	            window.location.href = \"/ddeStore/user/account.jsp\";\r\n");
      out.write("	        }, 3000);\r\n");
      out.write("	    });\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
